### ISSUE TITLE
mean and std in config.yaml

### ISSUE THREAD

**Issue by xiaozhuqian** [hayatrajani/s3seg-vit#1]
Thank you for your great work!

I'm trying to reproduce your code on my sonar dataset. But I'm confused about how you determine the mean and std of data in config.yaml. Are they the mean and standard deviation of all pixels in the dataset?

I'm looking forward to your reply.

Thank you.

**Comment by hayatrajani** [comment]
Thank you for your interest in our work.

Those are (approximate) per-channel mean and standard deviation computed across the training dataset. Perhaps this block of code helps:
```
def computeMeanStd(train_loader):
    mean, std  = 0, 0
    samples = 0.
    for images, _ in train_loader:
        mean += torch.mean(images, dim=(0,2,3))
        std += torch.std(images, dim=(0,2,3))
        samples += 1
    mean /= samples
    std /= samples
    return mean, std
```

**Comment by xiaozhuqian** [comment]
Got it. Thank you.
